// Global configuration file - edit this file to change data for ALL users
window.globalCardData = {
    image: "https://imgur.com/a/8KtvObd",
    name: "Oskar",
    surname: "Sieczka", 
    nationality: "polskie",
    familyName: "Kalwat",
    fathersFamilyName: "Kalwat", 
    mothersFamilyName: "Nowak",
    birthPlace: "Kielce",
    countryOfBirth: "Polska",
    adress1: "ul. ściegiennego 23",
    adress2: "26-026", 
    city: "Bilcza",
    mothersName: "Marysia",
    fathersName: "Piotr",
    givenDate: "15/06/2017",
    expiryDate: "15/06/2027", 
    seriesAndNumber: "DJL18594",
    birthday: "05.09.2004",
    sex: "Mężczyzna",
    pesel: "04290561694",
    adress: "ul. ściegiennego 23 26-026, Bilcza",
    timestamp: "2025-09-23T23:35:26.091Z"
};
